lesson14pr
vitalyryzhkov/mateAcademyMaven pull request #9
Opened 2019-04-12 01:49 UTC by vitalyryzhkov

2019-04-13 00:15 UTC, Anderwerty requested changes

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/AbstractFactory.java
> +public class AbstractFactory {
Logic should be in the main method. Move it into a seperate class.

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/RuFerrariImpl.java
> +        return 30000;
Is better to use constant for this number.
Example:
`private static final int MAX_SPEED=3000;`

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/RuLadaImpl.java
> +        return 10000;
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/RuPorsheImpl.java
> +        return 20000;
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/UaFerrariImpl.java
> +        return 3000;
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/UaLadaImpl.java
> +        return 1000;
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/UaPorsheImpl.java
> +        return 2000;
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Iphone.java
> +    public void getPrice() {
As it is getter is should return price value but not print result.
Please rename this method or change its signature.

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/IphoneAdapter.java
> +        samsung.getPrice();
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Samsung.java
> +    public void getPrice() {
The same

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Samsung.java
> +        price = 200;
200 looks like a magic number. Please use a constant.

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/factorymethod/Factory.java
> +        if (inputos.equals("windows")) {
1) Why not use a switch case instead of if else?
2)  inputos could be null. So, you could get NPE.  Please fix it.

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/flyweight/Factory.java
> +    public Factory(int maxRows) {
What if maxRows <0?

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/flyweight/Factory.java
> +    public Flyweight getFlyweight(int row) {
What if row <0?

2019-04-13 00:15 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/prototype/ComplicatedObject.java
> +public class ComplicatedObject implements Copyable {
Why not use interface Clonable?

2019-04-13 12:46 UTC, vitalyryzhkov commented on src/main/java/com/homework/lesson14/prototype/ComplicatedObject.java
> +public class ComplicatedObject implements Copyable {
Такой был в примере, его и использовал))

2019-04-13 14:44 UTC, Anderwerty requested changes

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/AbstractFactory.java
> +        if (country.equals("UA")) {
Please use a constant for "UA". Now it looks like a magic number.

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/AbstractFactory.java
> +        } else if (country.equals("RU")) {
The same

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Iphone.java
> +    private final int PRICE = 100;
You forgot modifier static.

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/factorymethod/Factory.java
> +                case "windows":
"windows" looks like a magic number. Please use a constant here.

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/factorymethod/Factory.java
> +                case "linux":
The same

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/factorymethod/Factory.java
> +                case "mac":
The same

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/flyweight/Factory.java
> +            pool = new Flyweight[maxRows];
In case maxRows<0 better to initialize by some default value or even throw a custom exception.

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/prototype/ComplicatedObject.java
> +//    @Override
Please if you don't need it, remove.

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/prototype/MyPrototype.java
> +            e.printStackTrace();
Why not use logger here?

2019-04-13 14:44 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/prototype/MyPrototype.java
> +        Objects.requireNonNull(clone).setType(ComplicatedObject.Type.ONE);
Please check in code (here) that prototype and clone is not the same object.

2019-04-14 13:21 UTC, Anderwerty requested changes

2019-04-14 13:21 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/AbstractFactory.java
> +    private static final String uaFactory = "UA";
Naming is not right.
https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2019-04-14 13:21 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/abstractfactory/AbstractFactory.java
> +    private static final String ruFactory = "RU";
The same

2019-04-15 08:40 UTC, Anderwerty approved these changes
Please fix

2019-04-15 08:40 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Adapter.java
> +        System.out.println(iphone + "\n"
Why not in one line?

2019-04-15 08:40 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/adapter/Samsung.java
> +    private final int PRICE = 200;
Forgot modifier static

2019-04-15 08:40 UTC, Anderwerty commented on src/main/java/com/homework/lesson14/factorymethod/Factory.java
> +    private static final String windowsOs = "windows";
Wrong naming style https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2019-04-15 13:24 UTC, merged